[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.33"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
ignored_error_codes = [2424, 4591]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
